version: "3.7"

services:
  client:
    container_name: $COMPOSE_PROJECT_NAME-client
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    expose:
      - 5173
    environment:
      HOST: 0.0.0.0
    networks:
      - app-network

  laravel:
    image: yaraku/assignment:$COMPOSE_PROJECT_NAME
    container_name: $COMPOSE_PROJECT_NAME-laravel
    environment:
      DB_DATABASE: laravel
      DB_HOST: mysql
      DB_PASSWORD: secret
      DB_USERNAME: laravel
      APP_DEBUG: 'true'
      APP_ENV: local
      APP_KEY: ayGbuqVXJakHHvMTZCjKqzhVqMNsHMQs
      LOG_CHANNEL: stderr
    ports:
    - '8080:80'
    volumes:
    - ./server:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: $COMPOSE_PROJECT_NAME-mysql
    ports:
    - '3306:3306'
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
volumes:
  mysql:
    driver: local